version: '2'
services:

  rabbitmq:
    container_name: echo-rabbit
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672

  redis:
    container_name: echo-redis
    image: redis:alpine

  node:
    container_name: echo-node
    build:
      context: ./docker/node
    volumes:
      - ./laravel-echo-server.json:/app/laravel-echo-server.json:ro
    ports:
      - 6001:6001

  php:
    container_name: echo-php
    build:
      context: ./docker/php
    working_dir: /var/www
    volumes:
    - .:/var/www:cached

  web:
    container_name: echo-web
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes_from:
    - php
    ports:
    - 8008:80

volumes:
  redisdata: