version: '2'
services:

  redis:
    image: redis:alpine

  node:
    build:
      context: ./docker/node
    volumes:
      - ./laravel-echo-server.json:/app/laravel-echo-server.json:ro
    ports:
      - 6001:6001

  php:
    build:
      context: ./docker/php
    working_dir: /var/www
    volumes:
    - .:/var/www:cached

  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes_from:
    - php
    ports:
    - 8008:80

volumes:
  redisdata: